### ISSUE TITLE
[Feat] 공통 컴포넌트 - 최근 본 상품

### ISSUE THREAD

**Issue by dabini99** [FRONTENDSCHOOL10/ssagwa-kurly#100]
🤷‍♂️ Description
---
최근 본 상품 데이터 받아와서 보여주기

📝 Check Point
---
- [x] 최근 본 상품 html,css하기
- [x] 데이터 불러오기

**Comment by jaehwan-space** [comment]
## 🤷‍♂️ Description

- 최근 본 상품 기능 구현

## 📝 Check Point

- [x] 상품 클릭 시 로컬스토리지에 상품 아이디, 배너 이미지, 클릭 시간 기록하기
- [x] 모든 페이지에 최근 본 상품 보여지기
- [x] 일정 너비 아래로 내려가면 안 보임 (1250px)
- [x] swiper를 통해 스와이퍼 버튼 클릭 시 이미지 아래로 내려가기
- [x] 상품 클릭 시 상품 페이지로 이동

## 📷 Screenshots


![Image](https://github.com/user-attachments/assets/9a8f4971-c834-426c-b546-929ae40d5570)
