### ISSUE TITLE
[Feat]팝업 모달창

### ISSUE THREAD

**Issue by dabini99** [FRONTENDSCHOOL10/ssagwa-kurly#114]
🤷‍♂️ Description
- 사이트 방문시 팝업 모달창 구현

📝 Check Point
- [X] 팝업 모달창 구현

**Comment by jaehwan-space** [comment]
## 🤷‍♂️ Description
- 메인페이지 팝업창 기능 구현
## 📝 Check Point
- [x]  오늘 하루동안 보지 않기 선택 시 당일에 보이지 않기
- [x] 메인페이지 새로고침 및 접속했을 때 팝업 보이기
## 📷 Screenshots(선택)
![image](https://github.com/user-attachments/assets/d6eeb65b-9d9f-4937-86fe-8b40b52c022a)
