### ISSUE TITLE
[BugFix] 배포 전 버그 수정

### ISSUE THREAD

**Issue by jaehwan-space** [FRONTENDSCHOOL10/ssagwa-kurly#160]
## 🤷‍♂️ Description
- 최종 배포 전 버그 수정
## 📝 Check Point
- [x] header 카테고리 아이콘 작아지는 문제
- [x] 메인 페이지 배너 스와이퍼 이미지 찌그러지는 문제
- [x] 메인 페이지 마크업 오류 (witth, height 스타일 요소 안에 있지 않음)

## 📷 Screenshots

![Image](https://github.com/user-attachments/assets/c32c3af9-0cf5-4815-b5f5-cadd67a1a271)
![Image](https://github.com/user-attachments/assets/66394cce-629a-4a88-b7ba-b00fc69cc174)

**Comment by chlyun** [comment]
header.js  수정
```
<img src="/svg/Hamburger.svg" alt="카테고리" class="nav__category-hambuger" />
```

header.css 수정
```
//삭제
.nav__category img {                 
  margin-right: 0.75rem;
  width: 1rem;
  height: 0.875rem;
}
//추가
.nav__category-hambuger {
  margin-right: 0.75rem;
  width: 1rem;
  height: 0.875rem;
}
//추가
.nav__category__item-title {
  margin-left: 0.75rem;
  font-size: 0.875rem;
}
```
