### ISSUE TITLE
[Feat] 상품데이터 pocketbase 연동

### ISSUE THREAD

**Issue by chlyun** [FRONTENDSCHOOL10/ssagwa-kurly#45]
## 🤷‍♂️ Description
상품데이터 pocketbase 연결해두기
## 📝 Check Point

- [x] pocketbase.js export해두기
- [x] pocketbase에쓸 함수만들어두기

**Comment by jaehwan-space** [comment]
# 코드 리뷰 (PR Review)
1. 환경 변수 설정 필요
  - 현재 환경 변수가 코드 내에 하드코딩 되어 있습니다. 프로젝트의 환경 변수 관리를 위해 .env 파일을 생성하고 사용하는 것을 권장드립니다. 이렇게 하면 코드의 가독성과 보안성이 향상됩니다.
  - 예를 들어, 프로젝트 루트 디렉터리에 .env 파일을 생성하고 다음과 같이 환경 변수를 설정하세요:
    ```
    VITE_PB_URL=https://your-pocketbase-url.com
    ```
  - 그런 다음, import.meta.env.VITE_PB_URL를 통해 환경 변수를 접근할 수 있습니다. 이렇게 하면 배포 환경에 따라 쉽게 설정을 변경할 수 있습니다.
  
  ---
  감사합니다.
